# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  fmt_and_build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      # Rust is automatically set up and included by default according to: https://github.com/actions/starter-workflows/blob/master/ci/rust.yml
      # Run cargo fmt linting on the source code
      - name: Run style linter
        run: cargo fmt -- --check

      # Run the build to make sure it also compiles
      - name: Run build
        run: cargo build