name: MAIN

on:
  # push:
  #   branches: [main]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Emit repository_dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.GH_PAT }}
          repository: iasql/iasql-on-iasql
          event-type: code_change
          client-payload: '{"ref": "${{ github.ref }}"}'