name: Release CLI

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

env:
  VERSION: $(echo ${{github.ref}} | sed "s/refs\/tags\/v//")

jobs:
  ubuntu:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generate IaSQL tar.gz
      run: |
        cargo build --release
        cd ./target/release
        tar -czf /tmp/iasql-ubuntu.tar.gz iasql

    - name: Upload IaSQL zip
      uses: softprops/action-gh-release@v1
      with:
        files: /tmp/iasql-ubuntu.tar.gz

    - name: Generate IaSQL Debian package
      run: |
        sudo apt install checkinstall -y
        echo "Infrastructure as SQL (IaSQL) CLI client" | sudo checkinstall --install=no -D --pkgname=iasql --pkgversion=${iasqlversion} --pkglicense=Proprietary --maintainer=hello@iasql.com --pkggroup="IaSQL" --nodoc --deldesc=yes --delspec=yes --backup=no
        cp ./iasql_${{ env.VERSION }}-1_amd64.deb /tmp/iasql_ubuntu_amd64.deb

    - name: Upload IaSQL Debian package
      uses: softprops/action-gh-release@v1
      with:
        files: /tmp/iasql_ubuntu_amd64.deb

  windows:
    runs-on: windows-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generate IaSQL zip
      run: |
        cargo build --release
        Compress-Archive -Path "$(Join-Path (Get-Location).Path '\\target\\release\\iasql.exe')" -DestinationPath "$(Join-Path (Get-Location).Path 'iasql-windows.zip')"

    - name: Upload IaSQL zip
      uses: softprops/action-gh-release@v1
      with:
        files: D:\a\cli\cli\iasql-windows.zip

  macos:
    runs-on: macos-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Generate IaSQL tar.gz
      run: |
        cargo build --release
        cd ./target/release
        gtar -czf /tmp/iasql-macos.tar.gz iasql

    - name: Upload IaSQL tar.gz
      uses: softprops/action-gh-release@v1
      with:
        files: /tmp/iasql-macos.tar.gz

  docs:
    runs-on: ubuntu-latest
    needs:
      - ubuntu
      - macos
      - windows

    steps:
    - name: Emit repository_dispatch
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.GH_PAT }}
        repository: iasql/docs
        event-type: release
        client-payload: '{"version": "${{ env.VERSION }}"}'